[package]
name = "feel"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    ".",
    "./crates/feel_entity",
    "cmd/feel_api",
    "crates/feel_core",
    "crates/feel_sea_orm",
    "crates/feel_storage",
    "crates/migration",
]

[workspace.dependencies]
sea-orm = { version = "1.0", features = [
    "runtime-tokio-native-tls",
    "chrono",
    "sqlx-postgres",
] }
async-trait = "0.1"
