[package]
name = "feel_api"
version = "0.1.0"
edition = "2024"

[dependencies]
feel_entity = { path = "../../crates/feel_entity" }
feel_storage = { path = "../../crates/feel_storage" }
feel_core = { path = "../../crates/feel_core" }
migration = { path = "../../crates/migration" }

poem = { version = "3.1" }
redis = { version = "0.25", features = ["tokio-comp"] }
sea-orm.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
